apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-07T14:35:26Z"
  labels:
    app: greeting-dplmnt
  name: greeting-svc
  namespace: default
  resourceVersion: "1062"
  uid: a7342d40-7860-48d2-92df-4c7d0af442bc
spec:
  clusterIP: 10.43.167.173
  clusterIPs:
  - 10.43.167.173
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31877
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: greeting-dplmnt
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
